filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      match_source: true
      match_source_index: 5

output.logstash:
  hosts: ["logstash:5044"]
