server.port=8083
spring.application.name=product-service

# Database H2 (in-memory, cocok untuk development)
spring.jpa.hibernate.ddl-auto=update

# Eureka Client — daftar ke Eureka Server
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.enabled=true
management.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
