apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-auth
  template:
    metadata:
      labels:
        app: mysql-auth
    spec:
      containers:
        - name: mysql-auth
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: authdb
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-auth
spec:
  selector:
    app: mysql-auth
  ports:
    - port: 3306
      targetPort: 3306
