FROM openjdk:27-ea-17-jdk-slim-trixie
WORKDIR /app
COPY target/email-service-0.0.1-SNAPSHOT.jar /app/app.jar 
EXPOSE 8084
ENTRYPOINT ["java", "-Dspring.h2.console.settings.web-allow-others=true", "-jar", "app.jar"]