server.port=8761
spring.application.name=eureka-service

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.enabled=true
management.health.show-details=always
management.metrics.export.prometheus.enabled=true