server.port=8083
spring.application.name=email-service

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zalnamustika111@gmail.com
spring.mail.password=kuhw bdys qfce lpzj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
